spring:
  profiles:
    #?????
    active: test
  application:
    name: mallchat
  datasource:
    url: jdbc:mysql://${mallchat.mysql.ip}:${mallchat.mysql.port}/${mallchat.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${mallchat.mysql.username}
    password: ${mallchat.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis?????
    host: ${mallchat.redis.host}
    # Redis??????
    port: ${mallchat.redis.port}
    # ????????????0
    database: 0
    # ??????
    timeout: 1800000
    # ????
    password: ${mallchat.redis.password}
  jackson:
    serialization:
      write-dates-as-timestamps: true